Importing Library and dataset

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("heart.csv")

In [3]:
df.head()

age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  oldpeak  slp  \
0   63    1   3     145   233    1        0       150     0      2.3    0   
1   37    1   2     130   250    0        1       187     0      3.5    0   
2   41    0   1     130   204    0        0       172     0      1.4    2   
3   56    1   1     120   236    0        1       178     0      0.8    2   
4   57    0   0     120   354    0        1       163     1      0.6    2   

   caa  thall  output  
0    0      1       1  
1    0      2       1  
2    0      2       1  
3    0      2       1  
4    0      2       1

In [4]:
df.shape

(303, 14)

In [5]:
df.isnull().sum().sort_values(ascending=False)

age         0
sex         0
cp          0
trtbps      0
chol        0
fbs         0
restecg     0
thalachh    0
exng        0
oldpeak     0
slp         0
caa         0
thall       0
output      0
dtype: int64

Selecting Target and feature values

In [6]:
x = df.iloc[:,:-1].values
y = df.iloc[:,-1]

In [7]:
x

array([[63.,  1.,  3., ...,  0.,  0.,  1.],
       [37.,  1.,  2., ...,  0.,  0.,  2.],
       [41.,  0.,  1., ...,  2.,  0.,  2.],
       ...,
       [68.,  1.,  0., ...,  1.,  2.,  3.],
       [57.,  1.,  0., ...,  1.,  1.,  3.],
       [57.,  0.,  1., ...,  1.,  1.,  2.]])

In [8]:
y

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: output, Length: 303, dtype: int64

Test_train_split

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=1)

In [10]:
x_train

array([[51.,  1.,  3., ...,  2.,  1.,  2.],
       [44.,  1.,  0., ...,  2.,  1.,  2.],
       [54.,  1.,  0., ...,  1.,  1.,  3.],
       ...,
       [29.,  1.,  1., ...,  2.,  0.,  2.],
       [51.,  1.,  0., ...,  2.,  0.,  3.],
       [54.,  1.,  2., ...,  2.,  0.,  3.]])

In [11]:
y_train

34     1
185    0
187    0
147    1
202    0
      ..
203    0
255    0
72     1
235    0
37     1
Name: output, Length: 212, dtype: int64

**Fitting Model**

Random forest Classifier

In [12]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators= 10, criterion="entropy")
classifier.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10)

In [13]:
y_pred = classifier.predict(x_test)

In [14]:
y_pred

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 0])

Discussion about accuracy and model

In [15]:
from sklearn.metrics import confusion_matrix,classification_report
print(confusion_matrix(y_test,y_pred))

[[34  7]
 [13 37]]


In [16]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.72      0.83      0.77        41
           1       0.84      0.74      0.79        50

    accuracy                           0.78        91
   macro avg       0.78      0.78      0.78        91
weighted avg       0.79      0.78      0.78        91



In [17]:
classifier.score(x_test,y_test)

0.7802197802197802

Naive Bayes

In [18]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(x_train, y_train)

GaussianNB()

In [19]:
y_pred = gnb.predict(x_test)

In [20]:
from sklearn.metrics import confusion_matrix,classification_report
print(confusion_matrix(y_test,y_pred))

[[32  9]
 [10 40]]


In [21]:
gnb.score(x_test,y_test)

0.7912087912087912

Logistic Regression

In [22]:
from sklearn.linear_model import LogisticRegression
#Now create object of LogisticRegression
logisModel = LogisticRegression()
#And now fit the model into x_train and y_train
logisModel.fit(x_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression()

In [23]:
y_pred = logisModel.predict(x_test)

In [24]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))


              precision    recall  f1-score   support

           0       0.81      0.73      0.77        41
           1       0.80      0.86      0.83        50

    accuracy                           0.80        91
   macro avg       0.80      0.80      0.80        91
weighted avg       0.80      0.80      0.80        91



In [25]:
print(confusion_matrix(y_test,y_pred))

[[30 11]
 [ 7 43]]


In [26]:
logisModel.score(x_test,y_test)

0.8021978021978022

K nearest Neigbour

In [29]:
from sklearn.neighbors import KNeighborsClassifier 
classifi = KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2) 
classifi.fit(x_train,y_train)

KNeighborsClassifier()

In [30]:
from sklearn.metrics import confusion_matrix,classification_report
print(confusion_matrix(y_test,y_pred))

[[30 11]
 [ 7 43]]


In [31]:
classifi.score(x_test,y_test)

0.5934065934065934